### ISSUE TITLE
cdetect detects wrong version

### ISSUE THREAD

**Issue by ghost** [xyproto/cdetect#1]
Hi @xyproto ! 

I managed to create a package for Void linux, see PR [#9176](https://github.com/voidlinux/void-packages/pull/9176). 

But there's a problem: we use GCC 7.2.0, but cdetect wrongly detects version 6.3.0 instead. 

How is that possible ?? 

Thank you!

**Comment by xyproto** [comment]
Thanks for reporting, I want to fix this. Do you have an example ELF executable?

**Comment by ghost** [comment]
For example [nano](https://github.com/voidlinux/void-packages/pull/9312) was updated 2 days ago. 
Installed it, and when I run cdetect: 
````
$ cdetect /usr/bin/nano
GCC 6.3.0
````

**Comment by xyproto** [comment]
Installing Void Linux in a virtual machine now, to try to figure this one out.

**Comment by xyproto** [comment]
The nano executable contains this data:

`GCC: (GNU) 6.3.0.GCC: (GNU) 7.2.0`

I will make modifications to cdetect so that it extracts the correct version number.

**Comment by xyproto** [comment]
Fixed. Please let me know if there should be further issues with this. Thank you!

**Comment by ghost** [comment]
````
$ cdetect /usr/bin/nano
GCC 7.2.0
````
it's good, thank you!
