### ISSUE TITLE
Downloading and building issue

### ISSUE THREAD

**Issue by vamsirocks** [xyproto/cdetect#2]
I want to checkout but after that what are the steps to generate cDetect utility . Please provide step by step procedure to generate cDetect utility after cloning from git. The command i found in the README ( go get -u github.com/xyproto/cdetect ) file executed but unable to get the cDetect utility . I am trying on ubuntu 18.04 64 bit

**Comment by xyproto** [comment]
Ah, yes, Go 1.12 or later is required. Added a note in the README.md file. Thanks for reporting.
